/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPanelFondoPrincipal.java
 *
 * Created on 04/09/2010, 01:25:17 PM
 */
package CapaPresentacion;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Richard
 */
public class FrmPanelFondoPrincipal extends javax.swing.JPanel {

    /** Creates new form FrmPanelFondoPrincipal */
    public FrmPanelFondoPrincipal() {
        initComponents();
        this.setSize(500, 400);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @Override
    public void paintComponent(Graphics g) {
        Dimension d = getSize();
        ImageIcon img = new ImageIcon(getClass().getResource("/ComponenteImagenes/Fondo-Present-1.jpg"));
        g.drawImage(img.getImage(), 0, 0, d.width, d.height, this);
        setOpaque(false);
        super.paintComponent(g);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
