/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmLogin.java
 *
 * Created on 03/09/2010, 10:45:12 AM
 */
package CapaPresentacionInicio;


import CapaBusiness.EmpleadoBL;
import CapaBusiness.UsuarioBL;
import CapaEntidades.EmpleadoBE;
import CapaEntidades.UsuarioBE;
import CapaPresentacion.FrmMenu;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Richard
 */
public abstract class FrmInicioSesion extends javax.swing.JFrame {
    /** Creates new form FrmLogin */
    public FrmInicioSesion() {
        this.setUndecorated(true);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new FrmPanelFondoLogin();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        botonIngresar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("PASSWORD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("USUARIO:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtClave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtClave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtClave.setPreferredSize(new java.awt.Dimension(105, 21));
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 95;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 0, 10);
        jPanel1.add(txtClave, gridBagConstraints);

        botonIngresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonIngresar.setText("Ingresar");
        botonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 7, 0);
        jPanel1.add(botonIngresar, gridBagConstraints);

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 7, 0);
        jPanel1.add(botonSalir, gridBagConstraints);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtUsuario.setPreferredSize(new java.awt.Dimension(105, 21));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 95;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 0, 10);
        jPanel1.add(txtUsuario, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtUsuarioActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_botonSalirActionPerformed

    @SuppressWarnings("static-access")
    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
//                FrmMenu frmMP = new FrmMenu() {};
//                    frmMP.lblNomUserlogeado.setText("rmaldonado");
//                    frmMP.lblApUsuariologeado.setText("Ruben Omar Maldonado Cubas");
//                    frmMP.setVisible(true);
//                this.dispose();

//////        // TODO add your handling code here:
        String usuario = txtUsuario.getText();
        String clave = new String(txtClave.getPassword());
        if(!usuario.isEmpty() && !clave.isEmpty())
        {
           try {
               UsuarioBE usu = new UsuarioBE();
               UsuarioBL usuarioBL = new UsuarioBL();
               // usu = (UsuarioBE) dao.VerificarUsuario(usuario,clave);
               usu = usuarioBL.GetUsuario(usuario, clave);
                    
                if(usu != null)
                {
                    if (usu.usuEstado == 0){
                        
                        JOptionPane.showMessageDialog(this, "Su usuario esta desabilitado \n"
                                                        + "Comuniquese con el administrador ", 
                                            "Aviso Sistema",JOptionPane.ERROR_MESSAGE);
                        
                    }else{
                        
                        if (usuario.equals(usu.UsuLogeo) && clave.equals(usu.UsuContrasenia)) {

                                                   
                            // Llenando los datos del usuario
                            EmpleadoBE emp = new EmpleadoBE();
                            EmpleadoBL empleadoBL = new EmpleadoBL();
                            emp = empleadoBL.GetEmpleadoById(usu.idEmpleado);
                            if(emp != null){
                                String Completo = "";
                                Completo = emp.empApepat + ' '+emp.empApemat +' '+ emp.empNombres;
                                
                                FrmMenu frmMP = new FrmMenu() {};
                                frmMP.lblNomUserlogeado.setText(txtUsuario.getText());
                                //Llenando de la segunda consulta
                                frmMP.lblApUsuariologeado.setText(String.valueOf(Completo));
                                frmMP.setVisible(true);
                                this.dispose();
                            }else{
                                    JOptionPane.showMessageDialog(this, "Eror: Comuniquese con el administrador consulta 2", 
                                            "Error ... ",JOptionPane.ERROR_MESSAGE);      
                                }                            
                        }else{
                            JOptionPane.showMessageDialog(this, "Datos incorrectos: verifique su Nombre de usuario y contraseña\n"
                                                                +"Para conectarse use los siguientes datos de Prueba:\n", 
                                                "Error: Datos no Validos",JOptionPane.ERROR_MESSAGE);      
                        }
                    }
                }else{
                        JOptionPane.showMessageDialog(this, "Eror: Comuniquese con el administrador", 
                                            "Error ... ",JOptionPane.ERROR_MESSAGE);      
                    }
            } catch (Exception ex) {
                Logger.getLogger(FrmInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            } 
           
           
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese Usuario y contraseña.", 
                                        "Error: Ingrese sus datos de usuario",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FrmInicioSesion() {
                }.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
